bind 127.0.0.1 ::1
protected-mode yes
port 6379
daemonize no
supervised no
dir /Users/dahai/.linlinqi/data/redis
dbfilename dump.rdb
appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
save 900 1
save 300 10
save 60 10000
maxmemory 512mb
maxmemory-policy noeviction
aclfile /Users/dahai/.linlinqi/redis/users.acl
loglevel notice
logfile ""

