package supply

import (
	"context"
	"crypto/md5"
	"encoding/hex"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"net/url"
	"testing"
)

func TestACGSignatureMatchesPHPHTTPBuildQuerySemantics(t *testing.T) {
	values := url.Values{
		"a":     {"中文 空格"},
		"empty": {""},
		"sign":  {"ignored"},
		"sku":   {"甲 乙", "", "x+y"},
		"zero":  {"0"},
	}
	// Generated by the documented PHP implementation:
	// md5(urldecode(http_build_query($data).'&key=k+y%20z')).
	const expected = "9f33da13b90b0e5dc1fddc3ad1a8928a"
	if actual := acgSignature(values, "k+y%20z"); actual != expected {
		t.Fatalf("ACG signature mismatch: got %s want %s", actual, expected)
	}

	encoded := acgHTTPBuildQuery(values, true, true) + "&key=k+y%20z"
	digest := md5.Sum([]byte(phpURLDecode(encoded)))
	if hex.EncodeToString(digest[:]) != expected {
		t.Fatal("ACG canonical query no longer matches PHP urldecode semantics")
	}
}

func TestDecimalToMinorUnitsIsExact(t *testing.T) {
	for input, expected := range map[string]int64{
		"0": 0, "1": 100, "1.50": 150, "1.500": 150, "1e2": 10_000,
	} {
		actual, err := DecimalToMinorUnits(input, 2)
		if err != nil || actual != expected {
			t.Errorf("DecimalToMinorUnits(%q): got %d, %v; want %d", input, actual, err, expected)
		}
	}
	for _, input := range []string{"", "-1", "1.005", "NaN", "1/2", "999999999999999999999999"} {
		if _, err := DecimalToMinorUnits(input, 2); err == nil {
			t.Errorf("invalid amount %q was accepted", input)
		}
	}
}

func TestAPI7PurchaseUsesPOSTWithQuery(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if request.URL.Path != "/api/san-pham/mua" || request.Method != http.MethodPost {
			t.Fatalf("unexpected purchase request: %s %s", request.Method, request.URL.Path)
		}
		if request.URL.Query().Get("category") != "42" || request.URL.Query().Get("quantity") != "2" {
			t.Fatalf("purchase query mismatch: %s", request.URL.RawQuery)
		}
		if request.Header.Get("Authorization") != "Bearer purchase-token" {
			t.Fatalf("purchase authorization mismatch: %q", request.Header.Get("Authorization"))
		}
		writer.Header().Set("Content-Type", "application/json")
		_, _ = writer.Write([]byte(`{"success":{"status":"completed","products":["first","second"]}}`))
	}))
	defer server.Close()

	gateway, err := NewGateway("api-7", server.URL, map[string]string{"token": "purchase-token"}, true)
	if err != nil {
		t.Fatalf("construct API7 gateway: %v", err)
	}
	result, err := gateway.CreateOrder(context.Background(), CreateOrderRequest{ClientOrderNo: "local-1", ExternalProductID: "42", Quantity: 2})
	if err != nil || result.Status != "delivered" || len(result.Deliveries) != 2 {
		t.Fatalf("unexpected API7 order result: %#v, %v", result, err)
	}
}

func TestAPI13LegacyAccountIDUsesCanonicalUsernameSemantics(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if request.URL.Path != "/api/Service/Buy" || request.Method != http.MethodPost {
			t.Fatalf("unexpected API13 request: %s %s", request.Method, request.URL.Path)
		}
		if request.Header.Get("ApiKey") != "api-key" {
			t.Fatalf("API13 key header mismatch: %q", request.Header.Get("ApiKey"))
		}
		var body map[string]any
		if err := json.NewDecoder(request.Body).Decode(&body); err != nil {
			t.Fatalf("decode API13 body: %v", err)
		}
		if body["voucherCode"] != "legacy-user" || body["custom_UserId"] != "legacy-user" || body["custom_OrderId"] != "local-13" {
			t.Fatalf("API13 username semantics mismatch: %#v", body)
		}
		writer.Header().Set("Content-Type", "application/json")
		_, _ = writer.Write([]byte(`{"IsSuccessed":true,"Data":"remote-13"}`))
	}))
	defer server.Close()

	gateway, err := NewGateway("api-13", server.URL, map[string]string{"account_id": "legacy-user", "api_key": "api-key"}, true)
	if err != nil {
		t.Fatalf("construct API13 gateway with legacy credentials: %v", err)
	}
	result, err := gateway.CreateOrder(context.Background(), CreateOrderRequest{ClientOrderNo: "local-13", ExternalProductID: "13", Quantity: 1})
	if err != nil || result.ExternalOrderNo != "remote-13" {
		t.Fatalf("unexpected API13 order result: %#v, %v", result, err)
	}
}
