package router

import (
	"net/http"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"

	"linlinqi/api/internal/config"
	"linlinqi/api/internal/handler"
	"linlinqi/api/internal/middleware"
	"linlinqi/api/internal/security"
)

func New(cfg config.Config, db *gorm.DB, rdb *redis.Client, vault *security.Vault) *gin.Engine {
	if cfg.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}
	r := gin.New()
	if err := r.SetTrustedProxies(cfg.TrustedProxies); err != nil {
		panic("invalid TRUSTED_PROXIES: " + err.Error())
	}
	// JSON endpoints default to 1 MiB. The explicit multipart/callback routes
	// retain their documented limits with a small framing allowance.
	requestContext := middleware.RequestContextWithLimits(1<<20, map[string]int64{
		"/admin/v1/catalog/media/upload":                    cfg.MediaMaxImageBytes + (1 << 20),
		"/admin/v1/content/media/upload":                    cfg.MediaMaxImageBytes + (1 << 20),
		"/admin/v1/settings/media/upload":                   cfg.MediaMaxImageBytes + (1 << 20),
		"/admin/v1/supplier-category-mappings/media/upload": cfg.MediaMaxImageBytes + (1 << 20),
		"/admin/v1/reconciliations/import":                  9 << 20,
		"/api/v1/me/profile/avatar":                         cfg.MediaMaxImageBytes + (1 << 20),
		"/api/v1/payments/:channel/callback":                (2 << 20) + 1,
	})
	r.Use(requestContext, middleware.AccessLogger(), gin.Recovery(), middleware.Metrics(), middleware.I18N())
	r.Use(cors.New(cors.Config{
		AllowOrigins: cfg.CORSOrigins, AllowMethods: []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowOriginFunc: newResellerOriginChecker(db, cfg.Env == "production"),
		AllowHeaders:    []string{"Origin", "Content-Type", "Authorization", "X-API-Key", "X-Timestamp", "X-Nonce", "X-Signature", "X-Change-Reason", "X-Order-Token", "X-Storefront-Host", "X-Reseller-Code", "X-LinLinQi-Locale"},
		ExposeHeaders:   []string{"X-Request-ID"}, AllowCredentials: true, MaxAge: 12 * time.Hour,
	}))
	h := handler.Handler{DB: db, Cfg: cfg, Vault: vault, Redis: rdb}
	r.GET("/health", h.Health)
	r.GET("/live", h.Live)
	r.GET("/ready", h.Health)
	r.GET("/metrics", middleware.StaticBearer(cfg.MetricsToken), gin.WrapH(promhttp.Handler()))
	r.GET("/media/sha256/:prefix/:file", h.PublicMedia)
	r.GET("/", func(c *gin.Context) { c.JSON(http.StatusOK, gin.H{"service": "linlinqi-api", "version": "1.0.0"}) })

	api := r.Group("/api/v1")
	api.Use(middleware.IPBlocklist(db, "public", 15*time.Second))
	{
		api.GET("/store/config", h.StoreConfig)
		api.GET("/currencies", h.PublicCurrencies)
		api.GET("/currency-directory", h.PublicCurrencyDirectory)
		api.GET("/categories", h.Categories)
		api.GET("/products", h.Products)
		api.GET("/products/:slug", h.Product)
		api.GET("/payment-channels", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), h.PaymentChannels)
		api.POST("/checkout/quote", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "checkout-quote", 120, time.Minute), h.CheckoutQuote)
		api.GET("/content", h.PublicContent)
		api.GET("/posts/:slug", h.PublicPost)
		api.GET("/carts/:token", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), h.GetCart)
		api.PUT("/carts/:token/items", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "cart", 120, time.Minute), h.UpsertCartItem)
		api.DELETE("/carts/:token/items/:product_id", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "cart", 120, time.Minute), h.DeleteCartItem)
		api.POST("/cart-orders", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "store-order", 8, time.Minute), h.CreateCartOrder)
		api.POST("/orders", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "store-order", 8, time.Minute), h.CreateOrder)
		api.GET("/orders/:order_no", middleware.RateLimit(rdb, "order-query", 30, time.Minute), h.QueryOrder)
		api.POST("/orders/:order_no/payments", middleware.OptionalJWT(cfg.JWTSecret, "user"), middleware.OptionalActiveUser(db), middleware.RateLimit(rdb, "store-payment", 20, time.Minute), h.CreatePayment)
		api.POST("/payments/:channel/callback", middleware.RateLimit(rdb, "payment-callback", 600, time.Minute), h.PaymentCallback)
		api.POST("/supplier-callbacks/:supplier", middleware.RateLimit(rdb, "supplier-callback", 600, time.Minute), h.SupplierCallback)
		api.POST("/auth/register", middleware.RateLimit(rdb, "register", 8, time.Minute), h.Register)
		api.POST("/auth/login", middleware.RateLimit(rdb, "user-login", 12, time.Minute), h.UserLogin)
		api.POST("/auth/refresh", middleware.RateLimit(rdb, "user-refresh", 30, time.Minute), h.RefreshUserSession)
		api.POST("/auth/logout", middleware.RateLimit(rdb, "user-logout", 30, time.Minute), h.LogoutUserSession)
		api.POST("/auth/forgot", middleware.RateLimit(rdb, "user-forgot", 5, time.Hour), h.RequestPasswordReset)
		api.POST("/auth/reset", middleware.RateLimit(rdb, "user-reset", 10, time.Hour), h.ResetPassword)
		api.GET("/auth/oauth/providers", h.OAuthProviders)
		api.GET("/auth/oauth/:provider/start", middleware.RateLimit(rdb, "oauth-start", 20, time.Hour), h.StartOAuth)
		api.GET("/auth/oauth/:provider/callback", middleware.RateLimit(rdb, "oauth-callback", 40, time.Hour), h.OAuthCallback)
		api.POST("/auth/oauth/exchange", middleware.RateLimit(rdb, "oauth-exchange", 20, time.Hour), h.ExchangeOAuthCode)
	}
	user := api.Group("/me")
	user.Use(middleware.JWT(cfg.JWTSecret, "user"), middleware.ActiveUser(db))
	{
		user.GET("", h.Me)
		user.PATCH("/profile", h.UpdateMyProfile)
		user.POST("/profile/avatar", middleware.RateLimit(rdb, "user-avatar", 10, time.Hour), h.UploadMyAvatar)
		user.POST("/password", middleware.RateLimit(rdb, "user-password", 5, time.Hour), h.ChangeMyPassword)
		user.GET("/orders", h.MyOrders)
		user.GET("/wallet", h.MyWallet)
		user.GET("/recharges", h.MyRecharges)
		user.POST("/recharges", middleware.RateLimit(rdb, "wallet-recharge", 12, time.Hour), h.CreateRecharge)
		user.GET("/tickets", h.MyTickets)
		user.POST("/tickets", middleware.RateLimit(rdb, "ticket", 10, time.Hour), h.CreateTicket)
		user.GET("/tickets/:id", h.MyTicket)
		user.POST("/tickets/:id/messages", middleware.RateLimit(rdb, "ticket-reply", 30, time.Hour), h.ReplyMyTicket)
		user.GET("/reseller", h.MyReseller)
		user.POST("/reseller/apply", middleware.RateLimit(rdb, "reseller-apply", 3, 24*time.Hour), h.ApplyReseller)
		user.GET("/reseller/catalog", h.ResellerCatalog)
		user.GET("/reseller/orders", h.MyResellerOrders)
		user.POST("/reseller/domains", middleware.RateLimit(rdb, "reseller-domain", 10, 24*time.Hour), h.CreateResellerDomain)
		user.POST("/reseller/domains/:id/verify", middleware.RateLimit(rdb, "reseller-domain-verify", 20, time.Hour), h.VerifyResellerDomain)
		user.DELETE("/reseller/domains/:id", h.DeleteResellerDomain)
		user.PUT("/reseller/site", h.UpdateResellerSite)
		user.PUT("/reseller/product-rules/:product_id", h.UpsertResellerProductRule)
		user.GET("/reseller/withdrawals", h.MyResellerWithdrawals)
		user.POST("/reseller/withdrawals", middleware.RateLimit(rdb, "reseller-withdrawal", 5, 24*time.Hour), h.RequestResellerWithdrawal)
		user.GET("/gift-cards", h.MyGiftCards)
		user.POST("/gift-cards/redeem", middleware.RateLimit(rdb, "gift-card-redeem", 12, time.Hour), h.RedeemGiftCard)
		user.GET("/affiliate", h.MyAffiliate)
		user.POST("/affiliate/apply", middleware.RateLimit(rdb, "affiliate-apply", 3, 24*time.Hour), h.ApplyAffiliate)
		user.POST("/affiliate/withdrawals", middleware.RateLimit(rdb, "affiliate-withdrawal", 5, 24*time.Hour), h.RequestAffiliateWithdrawal)
		user.GET("/sessions", h.MySessions)
		user.GET("/notifications", h.MyNotifications)
		user.POST("/notifications/:id/read", h.MarkMyNotificationRead)
		user.DELETE("/sessions/:id", h.RevokeMySession)
		user.GET("/api-credentials", h.MyAPICredentials)
		user.POST("/api-credentials", middleware.RateLimit(rdb, "api-credential", 5, 24*time.Hour), h.CreateMyAPICredential)
		user.DELETE("/api-credentials/:id", middleware.RateLimit(rdb, "api-credential-revoke", 20, time.Hour), h.RevokeMyAPICredential)
		user.GET("/webhooks", h.MyWebhooks)
		user.POST("/webhooks", middleware.RateLimit(rdb, "webhook-endpoint", 10, 24*time.Hour), h.CreateMyWebhook)
		user.DELETE("/webhooks/:id", h.DeleteMyWebhook)
	}

	admin := r.Group("/admin/v1")
	admin.Use(middleware.IPBlocklist(db, "admin", 15*time.Second))
	admin.POST("/auth/login", middleware.RateLimit(rdb, "admin-login", 8, time.Minute), h.AdminLogin)
	protected := admin.Group("")
	protected.Use(middleware.JWT(cfg.AdminJWTSecret, "admin"), middleware.AdminSessionVersion(db), middleware.NoStore())
	{
		protected.GET("/auth/session", h.AdminSession)
		protected.GET("/dashboard", middleware.RequirePermission(db, "dashboard.read"), h.Dashboard)
		protected.GET("/analytics/overview", middleware.RequirePermission(db, "dashboard.read"), h.AdminAnalyticsOverview)
		protected.GET("/jobs", middleware.RequirePermission(db, "system.view"), h.AdminJobs)
		protected.GET("/jobs/summary", middleware.RequirePermission(db, "system.view"), h.AdminJobsSummary)
		protected.POST("/jobs/:id/retry", middleware.RequirePermission(db, "system.manage"), h.ReplayAdminJob)
		protected.POST("/jobs/batch-retry", middleware.RequirePermission(db, "system.manage"), h.BatchReplayAdminJobs)
		protected.GET("/operations/summary", middleware.RequirePermission(db, "dashboard.read"), h.OperationsSummary)
		protected.GET("/operations/reseller-profiles", middleware.RequirePermission(db, "reseller.view"), h.AdminResellerProfiles)
		protected.GET("/operations/reseller-domains", middleware.RequirePermission(db, "reseller.view"), h.AdminResellerDomains)
		protected.GET("/operations/reseller-wholesale-tiers", middleware.RequirePermission(db, "reseller.view"), h.AdminResellerWholesaleTiers)
		protected.GET("/integrations/summary", middleware.RequirePermission(db, "system.view"), h.AdminIntegrationSummary)
		protected.GET("/webhooks/endpoints", middleware.RequirePermission(db, "system.view"), h.AdminWebhookEndpoints)
		protected.PATCH("/webhooks/endpoints/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminWebhookEndpoint)
		protected.GET("/webhooks/deliveries", middleware.RequirePermission(db, "system.view"), h.AdminWebhookDeliveries)
		protected.POST("/webhooks/deliveries/:id/retry", middleware.RequirePermission(db, "system.manage"), h.RetryAdminWebhookDelivery)
		protected.GET("/notifications/templates", middleware.RequirePermission(db, "system.view"), h.AdminNotificationTemplates)
		protected.POST("/notifications/templates", middleware.RequirePermission(db, "system.manage"), h.CreateAdminNotificationTemplate)
		protected.PUT("/notifications/templates/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminNotificationTemplate)
		protected.DELETE("/notifications/templates/:id", middleware.RequirePermission(db, "system.manage"), h.DeleteAdminNotificationTemplate)
		protected.POST("/notifications/templates/:id/test", middleware.RequirePermission(db, "system.manage"), h.SendAdminNotificationTest)
		protected.GET("/notifications/deliveries", middleware.RequirePermission(db, "system.view"), h.AdminNotificationDeliveries)
		protected.POST("/notifications/deliveries/:id/retry", middleware.RequirePermission(db, "system.manage"), h.RetryAdminNotificationDelivery)
		protected.GET("/notifications/events", middleware.RequirePermission(db, "system.view"), h.AdminNotificationEvents)
		protected.GET("/notifications/subscriptions", middleware.RequirePermission(db, "system.view"), h.AdminNotificationSubscriptions)
		protected.POST("/notifications/subscriptions", middleware.RequirePermission(db, "system.manage"), h.CreateNotificationSubscription)
		protected.PUT("/notifications/subscriptions/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateNotificationSubscription)
		protected.DELETE("/notifications/subscriptions/:id", middleware.RequirePermission(db, "system.manage"), h.DeleteNotificationSubscription)
		protected.GET("/notifications/connectors", middleware.RequirePermission(db, "system.view"), h.AdminNotificationConnectors)
		protected.PUT("/notifications/connectors", middleware.RequirePermission(db, "system.manage"), h.SaveNotificationConnector)
		protected.GET("/operations/mappings", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplyMappings)
		protected.POST("/operations/mappings", middleware.RequirePermission(db, "supplier.manage"), h.CreateSupplyMapping)
		protected.PATCH("/operations/mappings/:id", middleware.RequirePermission(db, "supplier.manage"), h.UpdateSupplyMapping)
		protected.DELETE("/operations/mappings/:id", middleware.RequirePermission(db, "supplier.manage"), h.DeleteSupplyMapping)
		protected.GET("/operations/procurements", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplyProcurements)
		protected.GET("/operations/procurements/:id", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplyProcurementDetail)
		protected.POST("/operations/procurements/:id/retry", middleware.RequirePermission(db, "supplier.manage"), h.RetrySupplyProcurement)
		protected.POST("/operations/procurements/:id/manual-complete", middleware.RequirePermission(db, "supplier.manage"), h.CompleteSupplyProcurementManually)
		protected.GET("/operations/:resource", middleware.RequireOperationPermission(db), h.AdminResourceList)
		protected.POST("/operations/:resource", middleware.RequireOperationPermission(db), h.CreateAdminResource)
		protected.GET("/categories", middleware.RequireAnyPermission(db, "catalog.view", "supplier.view"), h.AdminCategories)
		protected.POST("/categories", middleware.RequirePermission(db, "catalog.manage"), h.CreateCatalogCategory)
		protected.PUT("/categories/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogCategory)
		protected.DELETE("/categories/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogCategory)
		protected.GET("/products", middleware.RequireAnyPermission(db, "catalog.view", "order.manage", "marketing.manage"), h.AdminProducts)
		protected.GET("/catalog/payment-channels", middleware.RequirePermission(db, "catalog.view"), h.AdminCatalogPaymentChannels)
		protected.GET("/catalog/media", middleware.RequirePermission(db, "catalog.view"), h.AdminCatalogMedia)
		protected.POST("/catalog/media/upload", middleware.RequirePermission(db, "catalog.manage"), h.UploadCatalogMedia)
		protected.POST("/catalog/media/mirror", middleware.RequirePermission(db, "catalog.manage"), h.MirrorCatalogMedia)
		protected.POST("/catalog/media", middleware.RequirePermission(db, "catalog.manage"), h.AttachCatalogMedia)
		protected.DELETE("/catalog/media/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogMedia)
		protected.POST("/products", middleware.RequirePermission(db, "catalog.manage"), h.CreateCatalogProduct)
		protected.PUT("/products/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogProduct)
		protected.PATCH("/products/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogProduct)
		protected.DELETE("/products/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogProduct)
		protected.GET("/products/:id/input-fields", middleware.RequireAnyPermission(db, "catalog.view", "order.manage"), h.AdminProductInputFields)
		protected.POST("/products/:id/input-fields", middleware.RequirePermission(db, "catalog.manage"), h.CreateProductInputField)
		protected.PUT("/product-input-fields/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateProductInputField)
		protected.DELETE("/product-input-fields/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteProductInputField)
		protected.PUT("/operations/variants/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogProductVariant)
		protected.DELETE("/operations/variants/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogProductVariant)
		protected.PUT("/operations/price-tiers/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogPriceTier)
		protected.DELETE("/operations/price-tiers/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogPriceTier)
		protected.PUT("/operations/member-levels/:id", middleware.RequirePermission(db, "catalog.manage"), h.UpdateCatalogMemberLevel)
		protected.DELETE("/operations/member-levels/:id", middleware.RequirePermission(db, "catalog.manage"), h.DeleteCatalogMemberLevel)
		protected.GET("/orders", middleware.RequireAnyPermission(db, "order.view", "payment.manage"), h.AdminOrders)
		protected.GET("/orders/export", middleware.RequirePermission(db, "order.view"), h.ExportAdminOrders)
		protected.POST("/orders/manual", middleware.RequirePermission(db, "order.manage"), h.CreateAdminManualOrder)
		protected.GET("/orders/:id", middleware.RequirePermission(db, "order.view"), h.AdminOrderDetail)
		protected.POST("/orders/:id/input-values/reveal", middleware.RequirePermission(db, "order.manage"), h.RevealAdminOrderInputValues)
		protected.POST("/orders/:id/transition", middleware.RequirePermission(db, "order.manage"), h.TransitionOrder)
		protected.GET("/inventory/products", middleware.RequirePermission(db, "inventory.view"), h.AdminInventoryProducts)
		protected.GET("/cards", middleware.RequirePermission(db, "inventory.view"), h.AdminInventoryCards)
		protected.POST("/cards/import", middleware.RequirePermission(db, "inventory.manage"), h.ImportInventoryCards)
		protected.PATCH("/cards/:id/status", middleware.RequirePermission(db, "inventory.manage"), h.UpdateInventoryCardStatus)
		protected.PATCH("/cards/batch-status", middleware.RequirePermission(db, "inventory.manage"), h.BatchUpdateInventoryCardStatus)
		protected.GET("/suppliers", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplySuppliers)
		protected.GET("/supplier-protocols", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplyProtocols)
		protected.POST("/suppliers", middleware.RequirePermission(db, "supplier.manage"), h.CreateSupplySupplier)
		protected.POST("/suppliers/sync-all", middleware.RequirePermission(db, "supplier.manage"), h.EnqueueAllSupplySupplierSync)
		protected.PATCH("/suppliers/:id", middleware.RequirePermission(db, "supplier.manage"), h.UpdateSupplySupplier)
		protected.DELETE("/suppliers/:id", middleware.RequirePermission(db, "supplier.manage"), h.DeleteSupplySupplier)
		protected.POST("/suppliers/:id/probe", middleware.RequirePermission(db, "supplier.manage"), h.AdminSupplierProbe)
		protected.POST("/suppliers/:id/quote", middleware.RequirePermission(db, "supplier.manage"), h.AdminSupplierQuote)
		protected.POST("/suppliers/:id/draft-cards", middleware.RequirePermission(db, "supplier.manage"), h.AdminSupplierDraftCards)
		protected.POST("/suppliers/:id/sync", middleware.RequirePermission(db, "supplier.manage"), h.EnqueueSupplySupplierSync)
		protected.GET("/suppliers/:id/sync-policy", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierSyncPolicy)
		protected.PUT("/suppliers/:id/sync-policy", middleware.RequirePermission(db, "supplier.manage"), h.UpdateSupplierSyncPolicy)
		protected.GET("/suppliers/:id/remote-categories", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierRemoteCategories)
		protected.GET("/suppliers/:id/remote-products", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierRemoteProducts)
		protected.POST("/suppliers/:id/import", middleware.RequirePermission(db, "supplier.manage"), h.ImportSupplierProducts)
		protected.GET("/suppliers/:id/import-jobs", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierImportJobs)
		protected.GET("/suppliers/:id/import-jobs/:job_id", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierImportJob)
		protected.POST("/suppliers/:id/import-jobs/:job_id/retry", middleware.RequirePermission(db, "supplier.manage"), h.RetrySupplierImportJob)
		protected.GET("/suppliers/:id/sync-runs", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierSyncRuns)
		protected.GET("/suppliers/:id/sync-runs/:run_id/changes", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierSyncRunChanges)
		protected.GET("/supplier-category-mappings", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierCategoryMappings)
		protected.GET("/supplier-category-mappings/summary", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplierCategoryMappingSummary)
		protected.POST("/supplier-category-mappings", middleware.RequirePermission(db, "supplier.manage"), h.CreateSupplierCategoryMapping)
		protected.PATCH("/supplier-category-mappings/batch-status", middleware.RequirePermission(db, "supplier.manage"), h.BatchUpdateSupplierCategoryMappingStatus)
		protected.DELETE("/supplier-category-mappings/batch", middleware.RequirePermission(db, "supplier.manage"), h.BatchDeleteSupplierCategoryMappings)
		protected.PUT("/supplier-category-mappings/:id", middleware.RequirePermission(db, "supplier.manage"), h.UpdateSupplierCategoryMapping)
		protected.DELETE("/supplier-category-mappings/:id", middleware.RequirePermission(db, "supplier.manage"), h.DeleteSupplierCategoryMapping)
		protected.POST("/supplier-category-mappings/media/upload", middleware.RequirePermission(db, "supplier.manage"), h.UploadCatalogMedia)
		protected.GET("/supply/catalog", middleware.RequirePermission(db, "supplier.view"), h.AdminSupplyCatalog)
		protected.GET("/users", middleware.RequirePermission(db, "customer.view"), h.AdminCustomers)
		protected.GET("/users/export", middleware.RequirePermission(db, "customer.view"), h.ExportAdminCustomers)
		protected.GET("/users/member-levels", middleware.RequirePermission(db, "customer.view"), h.AdminCustomerMembershipLevels)
		protected.GET("/users/:id", middleware.RequirePermission(db, "customer.view"), h.AdminCustomerDetail)
		protected.GET("/wallets/users", middleware.RequirePermission(db, "wallet.view"), h.AdminWalletCustomers)
		protected.GET("/wallets/users/export", middleware.RequirePermission(db, "wallet.view"), h.ExportAdminWalletCustomers)
		protected.GET("/wallets/users/:id", middleware.RequirePermission(db, "wallet.view"), h.AdminWalletCustomerDetail)
		protected.PATCH("/users/:id/status", middleware.RequirePermission(db, "customer.manage"), h.UpdateAdminCustomerStatus)
		protected.PATCH("/users/batch-status", middleware.RequirePermission(db, "customer.manage"), h.BatchUpdateAdminCustomerStatus)
		protected.PUT("/users/:id/membership", middleware.RequirePermission(db, "customer.manage"), h.GrantAdminCustomerMembership)
		protected.POST("/users/:id/membership/revoke", middleware.RequirePermission(db, "customer.manage"), h.RevokeAdminCustomerMembership)
		protected.POST("/users/:id/membership/recalculate", middleware.RequirePermission(db, "customer.manage"), h.RecalculateAdminCustomerMembership)
		protected.POST("/users/:id/wallet-adjustments", middleware.RequirePermission(db, "wallet.manage"), h.CreateAdminWalletAdjustment)
		protected.GET("/payments", middleware.RequirePermission(db, "payment.view"), h.AdminPayments)
		protected.GET("/recharges", middleware.RequirePermission(db, "payment.view"), h.AdminRecharges)
		protected.POST("/payments", middleware.RequirePermission(db, "payment.manage"), h.CreatePaymentChannel)
		protected.PATCH("/payments/:id", middleware.RequirePermission(db, "payment.manage"), h.UpdatePaymentChannel)
		protected.POST("/refunds", middleware.RequirePermission(db, "payment.manage"), h.CreateRefund)
		protected.POST("/reconciliations/import", middleware.RequirePermission(db, "payment.manage"), h.ImportReconciliation)
		protected.GET("/reconciliations/:id", middleware.RequirePermission(db, "payment.view"), h.ReconciliationDetail)
		protected.PATCH("/reconciliation-items/:id", middleware.RequirePermission(db, "payment.manage"), h.ResolveReconciliationItem)
		protected.GET("/gift-card-batches", middleware.RequirePermission(db, "marketing.view"), h.AdminGiftCardBatches)
		protected.POST("/gift-card-batches", middleware.RequirePermission(db, "marketing.manage"), h.IssueGiftCardBatch)
		protected.PATCH("/gift-card-batches/:id", middleware.RequirePermission(db, "marketing.manage"), h.DisableGiftCardBatch)
		protected.GET("/gift-cards", middleware.RequirePermission(db, "marketing.view"), h.AdminGiftCards)
		protected.PATCH("/gift-cards/:id/status", middleware.RequirePermission(db, "marketing.manage"), h.UpdateGiftCardStatus)
		protected.GET("/marketing/promotions", middleware.RequirePermission(db, "marketing.view"), h.AdminPromotions)
		protected.POST("/marketing/promotions", middleware.RequirePermission(db, "marketing.manage"), h.CreatePromotion)
		protected.PUT("/marketing/promotions/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdatePromotion)
		protected.GET("/marketing/coupons", middleware.RequirePermission(db, "marketing.view"), h.AdminCoupons)
		protected.POST("/marketing/coupons", middleware.RequirePermission(db, "marketing.manage"), h.CreateCoupon)
		protected.PUT("/marketing/coupons/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateCoupon)
		protected.GET("/content/categories", middleware.RequirePermission(db, "marketing.view"), h.AdminContentCategories)
		protected.POST("/content/categories", middleware.RequirePermission(db, "marketing.manage"), h.CreateContentCategory)
		protected.PUT("/content/categories/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateContentCategory)
		protected.DELETE("/content/categories/:id", middleware.RequirePermission(db, "marketing.manage"), h.DeleteContentCategory)
		protected.GET("/content/posts", middleware.RequirePermission(db, "marketing.view"), h.AdminContentPosts)
		protected.POST("/content/posts", middleware.RequirePermission(db, "marketing.manage"), h.CreateContentPost)
		protected.PUT("/content/posts/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateContentPost)
		protected.DELETE("/content/posts/:id", middleware.RequirePermission(db, "marketing.manage"), h.DeleteContentPost)
		protected.GET("/content/announcements", middleware.RequirePermission(db, "marketing.view"), h.AdminContentAnnouncements)
		protected.POST("/content/announcements", middleware.RequirePermission(db, "marketing.manage"), h.CreateContentAnnouncement)
		protected.PUT("/content/announcements/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateContentAnnouncement)
		protected.DELETE("/content/announcements/:id", middleware.RequirePermission(db, "marketing.manage"), h.DeleteContentAnnouncement)
		protected.GET("/content/banners", middleware.RequirePermission(db, "marketing.view"), h.AdminContentBanners)
		protected.POST("/content/banners", middleware.RequirePermission(db, "marketing.manage"), h.CreateContentBanner)
		protected.PUT("/content/banners/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateContentBanner)
		protected.DELETE("/content/banners/:id", middleware.RequirePermission(db, "marketing.manage"), h.DeleteContentBanner)
		protected.GET("/content/media", middleware.RequirePermission(db, "marketing.view"), h.AdminContentMedia)
		protected.POST("/content/media/upload", middleware.RequirePermission(db, "marketing.manage"), h.UploadContentMedia)
		protected.POST("/content/media", middleware.RequirePermission(db, "marketing.manage"), h.CreateContentMedia)
		protected.PUT("/content/media/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateContentMedia)
		protected.DELETE("/content/media/:id", middleware.RequirePermission(db, "marketing.manage"), h.DeleteContentMedia)
		protected.GET("/risk/rules", middleware.RequirePermission(db, "security.view"), h.AdminRiskRules)
		protected.POST("/risk/rules", middleware.RequirePermission(db, "security.manage"), h.CreateRiskRule)
		protected.PUT("/risk/rules/:id", middleware.RequirePermission(db, "security.manage"), h.UpdateRiskRule)
		protected.GET("/risk/decisions", middleware.RequirePermission(db, "security.view"), h.AdminRiskDecisions)
		protected.GET("/risk/summary", middleware.RequirePermission(db, "security.view"), h.AdminRiskSummary)
		protected.PATCH("/risk/decisions/:id/review", middleware.RequirePermission(db, "security.manage"), h.ReviewRiskDecision)
		protected.PATCH("/affiliates/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateAffiliateProfile)
		protected.GET("/affiliate-withdrawals", middleware.RequirePermission(db, "marketing.view"), h.AdminAffiliateWithdrawals)
		protected.GET("/affiliate-withdrawals/:id", middleware.RequirePermission(db, "marketing.view"), h.AffiliateWithdrawalDetail)
		protected.PATCH("/affiliate-withdrawals/:id", middleware.RequirePermission(db, "marketing.manage"), h.UpdateAffiliateWithdrawal)
		protected.PATCH("/resellers/:id", middleware.RequirePermission(db, "reseller.manage"), h.UpdateResellerProfile)
		protected.PUT("/reseller-wholesale-tiers/:level", middleware.RequirePermission(db, "reseller.manage"), h.PutResellerWholesaleTier)
		protected.PATCH("/reseller-domains/:id", middleware.RequirePermission(db, "reseller.manage"), h.UpdateResellerDomain)
		protected.GET("/reseller-withdrawals", middleware.RequirePermission(db, "reseller.view"), h.AdminResellerWithdrawals)
		protected.GET("/reseller-withdrawals/:id", middleware.RequirePermission(db, "reseller.view"), h.ResellerWithdrawalDetail)
		protected.POST("/reseller-withdrawals/:id/reveal", middleware.RequirePermission(db, "reseller.manage"), h.RevealResellerWithdrawalAccount)
		protected.PATCH("/reseller-withdrawals/:id", middleware.RequirePermission(db, "reseller.manage"), h.UpdateResellerWithdrawal)
		protected.GET("/tickets/:id", middleware.RequirePermission(db, "order.view"), h.AdminTicket)
		protected.POST("/tickets/:id/messages", middleware.RequirePermission(db, "order.manage"), h.ReplyAdminTicket)
		protected.PATCH("/tickets/:id", middleware.RequirePermission(db, "order.manage"), h.UpdateTicket)
		protected.GET("/settings", middleware.RequirePermission(db, "system.view"), h.AdminSettings)
		protected.PUT("/settings", middleware.RequirePermission(db, "system.manage"), h.SaveSettings)
		protected.POST("/settings/media/upload", middleware.RequirePermission(db, "system.manage"), h.UploadSettingsMedia)
		protected.GET("/currencies", middleware.RequirePermission(db, "system.view"), h.AdminCurrencies)
		protected.PATCH("/currencies/:code", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminCurrency)
		protected.GET("/fx/providers", middleware.RequirePermission(db, "system.view"), h.AdminFXProviders)
		protected.PATCH("/fx/providers/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminFXProvider)
		protected.GET("/fx/manual-rates", middleware.RequirePermission(db, "system.view"), h.AdminFXManualRates)
		protected.POST("/fx/manual-rates", middleware.RequirePermission(db, "system.manage"), h.CreateAdminFXManualRate)
		protected.PATCH("/fx/manual-rates/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminFXManualRate)
		protected.GET("/fx/snapshots", middleware.RequirePermission(db, "system.view"), h.AdminFXSnapshots)
		protected.POST("/fx/refresh", middleware.RequirePermission(db, "system.manage"), h.RefreshAdminFXRate)
		protected.GET("/access/overview", middleware.RequirePermission(db, "system.view"), h.AdminAccessOverview)
		protected.GET("/access/audit-logs", middleware.RequirePermission(db, "system.view"), h.AdminAccessAuditLogs)
		protected.POST("/access/admins", middleware.RequirePermission(db, "system.manage"), h.CreateAccessAdmin)
		protected.PATCH("/access/admins/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAccessAdmin)
		protected.POST("/access/admins/:id/password", middleware.RequirePermission(db, "system.manage"), h.ChangeAccessAdminPassword)
		protected.POST("/access/roles", middleware.RequirePermission(db, "system.manage"), h.CreateAccessRole)
		protected.PUT("/access/roles/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAccessRole)
		protected.DELETE("/access/roles/:id", middleware.RequirePermission(db, "system.manage"), h.DeleteAccessRole)
		protected.GET("/api-credentials", middleware.RequirePermission(db, "system.view"), h.AdminAPICredentials)
		protected.PATCH("/api-credentials/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAPICredential)
		protected.GET("/api-call-logs", middleware.RequirePermission(db, "system.view"), h.AdminAPICallLogs)
		protected.POST("/security/2fa/setup", h.BeginAdminTOTP)
		protected.GET("/security/2fa", h.AdminTOTPStatus)
		protected.POST("/security/2fa/verify", h.VerifyAdminTOTP)
		protected.POST("/security/sessions/revoke-all", h.RevokeAdminSessions)
		protected.GET("/security/events", middleware.RequirePermission(db, "system.view"), h.AdminSecurityEvents)
		protected.PATCH("/security/events/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateAdminSecurityEvent)
		protected.GET("/security/login-events", middleware.RequirePermission(db, "system.view"), h.AdminLoginEvents)
		protected.POST("/security/ip-blocklist", middleware.RequirePermission(db, "system.manage"), h.CreateIPBlock)
		protected.PATCH("/security/ip-blocklist/:id", middleware.RequirePermission(db, "system.manage"), h.UpdateIPBlock)
	}

	openapi := r.Group("/openapi/v1")
	openapi.Use(middleware.IPBlocklist(db, "openapi", 15*time.Second), middleware.RateLimit(rdb, "openapi", 600, time.Minute), middleware.OpenAPI(db, rdb, vault))
	{
		openapi.GET("/account/balance", h.OpenAPIBalance)
		openapi.GET("/categories", h.OpenAPICategories)
		openapi.GET("/products", h.OpenAPIProducts)
		openapi.GET("/products/:product_id", h.OpenAPIProduct)
		openapi.GET("/products/:product_id/stock", h.OpenAPIProductStock)
		openapi.POST("/products/:product_id/quote", h.OpenAPIProductQuote)
		openapi.POST("/orders", h.OpenAPICreateOrder)
		openapi.GET("/orders/:order_no", h.OpenAPIOrder)
	}
	return r
}
